# Generated by Django 3.2 on 2021-04-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
    ]
