# Generated by Django 3.2 on 2021-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
