# Generated by Django 3.2 on 2021-05-02 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210502_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
