# Generated by Django 3.2 on 2021-05-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='author',
        ),
    ]
